datasources:
  postgres:
    url: jdbc:postgresql://postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: k3str4

kestra:
  server:
    basicAuth:
      enabled: false
      username: "admin@kestra.io"  # it must be a valid email address
      password: kestra
  repository:
    type: postgres
  storage:
    type: local
    local:
      basePath: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/
  tutorialFlows:
    enabled: false

micronaut:
  io:
    watch:
      enabled: true
      paths:
        - /app/flows
      
